// src/client/view/admin.svelte
<script>
  import { onMount } from 'svelte'
  import { openMenu, showSetting } from '../lib/stores'
  import { translate } from '../i18n'
  import global from './global.svelte'
  import Login from './adminLogin.svelte'
  import Comment from './adminComment.svelte'
  import Config from './adminConfig.svelte'

  import IconLogo from '../../../assets/svg/Logo.svg'
  import IconMenu from '../../../assets/svg/Menu.svg'
  import IconRefresh from '../../../assets/svg/Refresh.svg'
  import IconComment from '../../../assets/svg/Comment.svg'
  import IconConfig from '../../../assets/svg/Config.svg'
  import IconExit from '../../../assets/svg/Exit.svg'
  import IconClose from '../../../assets/svg/Close.svg'

  export let show

  const manageStr = 'admin.'
  const commentManageStr = manageStr + 'manage'

  $: open = false
  let isLogin,
    title,
    tab,
    isRefresh = true,
    comment = 'comment',
    adminDOM

  onMount(() => {
    if (!document.querySelector('#Discuss')) {
      const creatEle = document.createElement('div')
      creatEle.id = 'Discuss'
      creatEle.className = 'Discuss'
      adminDOM.parentNode.insertBefore(creatEle, adminDOM)
      creatEle.appendChild(adminDOM)
    }
    onActiveTab()
  })

  function onRefresh() {
    isRefresh = false
    setTimeout(() => {
      isRefresh = true
    }, 1000)
  }
  function onActiveTab(key) {
    tab = key || comment
    title = translate(commentManageStr + '.' + tab + '.text')
  }
  function onExit() {
    isLogin = false
    $showSetting = false
    localStorage.DToken = ''
  }
  function onOpenAndClose() {
    $showSetting = !$showSetting
  }
</script>

<svelte:component this={global} />
<div class="D-admin-container" bind:this={adminDOM} style={!$showSetting ? 'display:none' : ''}>
  {#if !isLogin}
    <Login on:onClose={onOpenAndClose} on:loginS={() => (isLogin = true)} />
  {/if}
  {#if isLogin}
    <div class="D-admin" style={!$showSetting ? 'display:none' : ''}>
      <header class="D-header D-select-none">
        <div class="logo"><IconLogo /></div>
        <nav>
          <span class="D-menu" style={tab !== 'config' ? 'display:none' : ''} on:click={() => ($openMenu = true)}
            ><IconMenu /></span
          >
          <span class="D-refresh" on:click={onRefresh}><IconRefresh /></span>
          <span class="D-comment" on:click={() => onActiveTab('comment')}><IconComment /></span>
          <span class="D-config" on:click={() => onActiveTab('config')}><IconConfig /></span>
          {#if show}
            <!-- 是否显示关闭以及退出登录，主要区分页面评论区评论管理与以及评论管理独立初始化 -->
            <span class="D-exit" on:click={onExit}><IconExit /></span>
            <span class="D-close" on:click={onOpenAndClose}><IconClose /></span>
          {/if}
        </nav>
      </header>

      <h1 class="D-title">{title}</h1>
      {#if isRefresh}
        <div class="D-main-container">
          {#if tab === 'comment'}
            <Comment />
          {:else if tab === 'config'}
            <Config />
          {/if}
        </div>
      {/if}
    </div>
  {/if}
</div>

<style lang="scss">
  .D-admin-container {
    top: 0;
    right: 0;
    color: #fff;
    width: 100%;
    height: 100%;
    padding: 0 1.25em;
    font-size: 20px /* 16/16 */;
    z-index: 999999;
    position: fixed;
    background: #13111c;

    :global(*) {
      font-size: 0.95em;
    }

    :global(.D-input) {
      width: 100%;
      height: 2.25em /* 36/16 */;
      color: #fff;
      font-size: 1em /* 16/16 */;
      z-index: 10;
      padding: 0 0.75em /* 12/16 */;
      margin-top: 0.5em /* 8/16 */;
      background: transparent;
      border-radius: 0.375em;
      border: 1px solid #33323e;
    }

    .D-admin {
      position: relative;
      display: flex;
      flex-direction: column;
      flex-grow: 1;
      width: 100%;
      height: inherit;
      margin: auto;
      max-width: 72.5em /* 1160/16 */;
    }

    .D-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      min-height: 3.75em /* 60/16 */;
      width: 100%;
      margin-left: auto;
      margin-right: auto;
    }

    nav {
      margin-right: 1em;
      display: flex;
      color: #878593;
      font-weight: 600;
      font-size: 0.875em /* 14/16 */;
      align-items: center;

      span {
        cursor: pointer;
      }

      span + span {
        margin-left: 1.25em /* 20/16 */;
      }
    }
    .D-menu {
      display: none;
    }

    .D-title {
      margin: 0;
      font-size: 1.2em /* 30/16 */;
      line-height: 1;
      font-weight: 700;
      padding: 0 0 1.2em;
    }

    :global(.D-manage),
    :global(.D-main) {
      display: flex;
      flex-direction: column;
      align-items: center;
      width: 100%;
      height: inherit;
      background-color: #181622;
      border: solid 1px #33323e;
      border-radius: 0.625em /* 10/16 */;
      overflow-y: hidden;
    }

    .D-main-container {
      position: relative;
      display: flex;
      height: inherit;
      overflow: hidden;
      margin-bottom: 1em;
    }

    :global(.D-manage) {
      margin: 0;
    }

    :global(::-webkit-scrollbar) {
      display: none;
    }

    :global(::-webkit-scrollbar-thumb) {
      background: #33323e;
      border-radius: 5px;
    }

    :global(::-webkit-scrollbar-track) {
      background: #13111c;
    }
  }

  @media (max-width: 768px) {
    .D-admin-container {
      padding: 0 0.4em;

      .D-menu {
        display: block;
      }
    }
  }
</style>

// src/client/components/admin.vue
<template>
  <div class="D-admin-container" ref="adminPanel" v-show="showAdmin">
    <div class="D-admin-loading" v-show="isLoading" v-html="iconLoading"></div>
    <div class="D-admin-login" v-show="showLogin">
      <div class="D-admin-dialog">
        <div class="D-admin-dialog-title">Discuss 评论管理</div>
        <div class="D-admin-dialog-input" ref="login">
          <input
            type="text"
            v-model="username"
            placeholder="请输入用户名"
            required
          />
          <input
            type="password"
            v-model="password"
            placeholder="请输入密码"
            required
          />
        </div>
        <div class="D-admin-dialog-action">
          <button
            class="D-cancel D-button D-button-default"
            @click="onCancel"
            v-text="'关闭'"
          ></button>
          <button
            class="D-login D-button D-button-primary"
            @click="onLogin"
            :disabled="disabled"
            v-html="isLogin ? iconLoading : '登录'"
          ></button>
        </div>
      </div>
    </div>

    <div class="D-panel" v-if="loginSuccess">
      <div class="D-admin-header">
        <div class="D-panel-title">Discuss 管理面板</div>
        <div class="D-tabs">
          <div class="D-tab-left">
            <div
              class="D-tab"
              :class="{ 'D-active': activeTabName === 'comment' }"
              @click="activeTabName = 'comment'"
            >
              评论管理
            </div>
            <div
              class="D-tab"
              :class="{ 'D-active': activeTabName === 'config' }"
              @click="activeTabName = 'config'"
            >
              配置管理
            </div>
          </div>
          <div class="D-tab-right">
            <div class="D-tab D-logout" @click="onLogout">退出登录</div>
            <div class="D-tab D-close" @click="onClose">关闭</div>
          </div>
        </div>
      </div>
      <D-comment v-show="activeTabName === 'comment'"></D-comment>
      <D-config v-show="activeTabName === 'config'"></D-config>
    </div>
  </div>
</template>

<script>
import DComment from './adminComment.vue'
import DConfig from './adminConfig.vue'

import iconLoading from '../assets/svg/loading.svg'
import request from '../lib/request'
import { ShakeError } from '../lib/utils'

export default {
  components: { DComment, DConfig },
  props: { showAdmin: Boolean },
  data() {
    return {
      username: '',
      password: '',
      confirm: '',
      isLogin: false,
      disabled: false,
      loginMsg: '登录',
      url: this.$D.serverURLs,
      isLoading: false,
      showLogin: true,
      loginSuccess: false,
      activeTabName: 'comment',
      iconLoading
    }
  },
  methods: {
    async VerifyToken() {
      // 验证token是否有效
      const token = localStorage.DiscussToken || ''

      if (token) {
        this.isLoading = true
        this.showLogin = false
        const { data } = await request({
          url: this.url,
          data: { type: 'LOGIN', token }
        })
        if (data && data.token) {
          this.isLoading = false
          this.loginSuccess = true
        } else {
          this.isLoading = false
          this.showLogin = true
        }
      }
    },
    async onLogin() {
      this.disabled = true
      this.isLogin = true
      const params = {
        url: this.url,
        data: {
          type: 'LOGIN',
          username: this.username,
          password: this.password
        }
      }
      // 登录验证
      const { data } = await request(params)
      if (!data) {
        ShakeError(this.$refs.login)
        this.disabled = false
        this.isLogin = false
        console.error('Discuss [INFO]: 请求失败')
        return
      }
      this.disabled = false
      this.isLogin = false
      this.showLogin = false
      this.loginSuccess = true
      localStorage.DiscussToken = data.token
    },
    onCancel() {
      const adminPanel = this.$refs.adminPanel
      adminPanel.classList.add('popOut')
      setTimeout(() => {
        this.$emit('cancel')
        adminPanel.classList.remove('popOut')
      }, 450)
    },
    onLogout() {
      this.onCancel()
      localStorage.DiscussToken = ''
      setTimeout(() => {
        this.showLogin = true
        this.loginSuccess = false
      }, 450)
    },
    onClose() {
      this.onCancel()
    }
  },
  async mounted() {
    await this.VerifyToken()
  }
}
</script>

<style scoped>
.D-admin-container {
  top: 0;
  right: 0;
  width: 100%;
  height: 100%;
  z-index: 999999;
  position: fixed;
  animation-duration: 0.5s;
  -webkit-animation-duration: 0.5s;
  background: rgba(0, 0, 0, 0.65);
  backdrop-filter: blur(3px);
  -webkit-backdrop-filter: blur(3px);
}

.D-admin-loading {
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  display: flex;
  position: absolute;
  justify-content: center;
  align-items: center;
}

.D-admin-loading :deep(.D-loading-svg) {
  width: 40px;
}

.D-admin-login {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  flex-direction: column;
  justify-content: center;
}

.D-admin-dialog {
  max-width: 300px;
}

.D-admin-dialog-title {
  color: #fff;
  font-weight: 700;
  font-size: 20px;
  text-align: center;
}

.D-admin-dialog-input {
  margin-top: 10px;
  margin-bottom: 4px;
}

.D-admin-dialog-input input {
  width: 100%;
  height: 40px;
  line-height: 40px;
  outline: none;
  margin-bottom: 10px;
  padding: 0 15px;
  color: #000;
  display: block;
  font-size: inherit;
  box-sizing: border-box;
  text-align: center;
  border-radius: 4px;
  border: 1px solid #a9aeb6;
  background-color: rgba(255, 255, 255, 0.9);
  -webkit-appearance: none;
}

.D-admin-dialog-input input:hover {
  border-color: #6c6f74;
}

.D-admin-dialog-action {
  display: flex;
  flex-direction: row;
  width: 100%;
}

.D-login {
  margin-left: 2px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.D-cancel {
  margin-right: 2px;
}

/* info */
.D-panel {
  height: 100vh;
  padding: 20px;
  display: flex;
  flex-direction: column;
}

.D-admin-header {
  width: 100%;
}

.D-panel-title {
  color: #fff;
  font-weight: 600;
  font-size: 30px;
  text-align: center;
}

.D-tabs {
  width: 100%;
  display: flex;
  margin-bottom: 1em;
  border-bottom: 2px solid #c0c4cc;
  justify-content: space-between;
}

.D-tab-left,
.D-tab-right {
  display: flex;
}
.D-tab:nth-last-child(1) {
  margin: 0;
}

.D-tab {
  display: inline;
  color: #c0c4cc;
  cursor: pointer;
  line-height: 1.8em;
  margin: 0 1em -2px 0;
}
.D-tab a {
  color: #c0c4cc;
}

.D-tab.D-active {
  color: #fff;
  border-bottom: 2px solid #fff;
}
</style>
