// src/client/components/footer.vue
<template>
  <div class="D-footer">
    Powered by <a href="https://Discuss.js.org" target="_blank">Discuss</a> v{{
      version
    }}
  </div>
</template>

<script>
import request from '../lib/request'

import packages from '../../../package.json'
const { version } = packages

export default {
  data() {
    return {
      version
    }
  },
  methods: {
    async getCounter() {
      const counterEle = document.getElementById('Discuss-Visitors')
      if (!counterEle) return

      const options = {
        url: this.$D.serverURLs,
        data: {
          type: 'COUNTER',
          path: this.$D.path
        }
      }

      const { data } = await request(options)

      if (data) counterEle.innerText = data
    }
  },
  mounted() {
    this.getCounter()
  }
}
</script>

<style scoped>
.D-footer {
  width: 100%;
  text-align: end;
  font-size: 0.75em;
  color: #999;
  margin-top: 1em;
}

.D-footer a {
  font-weight: bold;
  text-decoration: none;
  color: #00c4b6;
}
</style>

// src/client/view/footer.svelte
<script>
  import { onMount } from 'svelte'
  import { version } from '../../../package.json'
  import { options } from '../lib/stores'
  import request from '../lib/request'

  let D = $options

  onMount(() => {
    VisitStat()
  })

  async function VisitStat() {
    const counterEle = document.getElementById('Discuss-Visitors')
    if (!counterEle) return

    const options = {
      url: D.serverURLs,
      data: { type: 'COUNTER', path: D.path }
    }

    const { data } = await request(options)

    if (data) counterEle.innerText = data
  }
</script>

<div class="D-footer">
  Powered by <strong><a href="https://Discuss.js.org" target="_blank">Discuss</a></strong> v{version}
</div>

<style>
  .D-footer {
    text-align: right;
    font-size: 0.75em;
    margin-top: 1em;
  }
</style>
